/*teacherList mutation-type*/
export const RECEIVE_TEACHERS = 'RECEIVE_TEACHERS'
export const RECEIVE_TEACHERS_COUNT = 'RECEIVE_TEACHERS_COUNT'
export const RECEIVE_TEACHERS_LIMIT = 'RECEIVE_TEACHERS_LIMIT'
export const RECEIVE_TEACHERS_OFFSET = 'RECEIVE_TEACHERS_OFFSET'
export const RECEIVE_TEACHERS_ERRMSG = 'RECEIVE_TEACHERS_ERRMSG'
export const RECEIVE_TEACHERS_CURRLIST = 'RECEIVE_TEACHERS_CURRLIST'

/*teacher mutation-type*/
export const RECEIVE_TEACHER_ID = 'RECEIVE_TEACHER_ID'
export const RECEIVE_TEACHER_NAME = 'RECEIVE_TEACHER_NAME'
export const RECEIVE_TEACHER_SEX = 'RECEIVE_TEACHER_SEX'
export const RECEIVE_TEACHER_PIC = 'RECEIVE_TEACHER_PIC'
export const RECEIVE_TEACHER_IDCARD = 'RECEIVE_TEACHER_IDCARD'
export const RECEIVE_TEACHER_TEACHERID = 'RECEIVE_TEACHER_TEACHERID'
export const RECEIVE_TEACHER_BIRTHDAY = 'RECEIVE_TEACHER_BIRTHDAY'
export const RECEIVE_TEACHER_PHONE = 'RECEIVE_TEACHER_PHONE'
export const RECEIVE_TEACHER_GROUPLIST = 'RECEIVE_TEACHER_GROUPLIST'
export const RECEIVE_TEACHER_CTIME = 'RECEIVE_TEACHER_CTIME'
export const RECEIVE_TEACHER_UTIME = 'RECEIVE_TEACHER_UTIME'

/*groupList mutation-type*/
export const RECEIVE_GROUPS = 'RECEIVE_GROUPS'
export const RECEIVE_GROUPS_COUNT = 'RECEIVE_GROUPS_COUNT'
export const RECEIVE_GROUPS_LIMIT = 'RECEIVE_GROUPS_LIMIT'
export const RECEIVE_GROUPS_OFFSET = 'RECEIVE_GROUPS_OFFSET'
export const RECEIVE_GROUPS_ERRMSG = 'RECEIVE_GROUPS_ERRMSG'
export const RECEIVE_GROUPS_CURRLIST = 'RECEIVE_GROUPS_CURRLIST'

/*usersList mutation-type*/
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const RECEIVE_USERS_COUNT = 'RECEIVE_USERS_COUNT'
export const RECEIVE_USERS_LIMIT = 'RECEIVE_USERS_LIMIT'
export const RECEIVE_USERS_OFFSET = 'RECEIVE_USERS_OFFSET'
export const RECEIVE_USERS_ERRMSG = 'RECEIVE_USERS_ERRMSG'
export const RECEIVE_USERS_CURRLIST = 'RECEIVE_USERS_CURRLIST'

/*ratingForm mutation-type*/
export const RECEIVE_RATINGFORM = 'RECEIVE_RATINGFORM'
export const RECEIVE_RATINGFORM_COUNT = 'RECEIVE_RATINGFORM_COUNT'
export const RECEIVE_RATINGFORM_LIMIT = 'RECEIVE_RATINGFORM_LIMIT'
export const RECEIVE_RATINGFORM_OFFSET = 'RECEIVE_RATINGFORM_OFFSET'
export const RECEIVE_RATINGFORM_ERRMSG = 'RECEIVE_RATINGFORM_ERRMSG'
export const RECEIVE_RATINGFORM_CURRLIST = 'RECEIVE_RATINGFORM_CURRLIST'
